# Generated by Django 5.0 on 2026-05-03 10:27

import sqlalchemy.sql._elements_constructors
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids')], max_length=50)),
                ('image', models.ImageField(null=sqlalchemy.sql._elements_constructors.true, upload_to='')),
                ('new_price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('is_popular', models.BooleanField(default=sqlalchemy.sql._elements_constructors.false)),
                ('is_new', models.BooleanField(default=sqlalchemy.sql._elements_constructors.false)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
