# Generated by Django 5.0 on 2026-05-03 11:02

import sqlalchemy.sql._elements_constructors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(null=sqlalchemy.sql._elements_constructors.true),
        ),
    ]
