# Generated by Django 5.2.15 on 2026-07-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productview_searchhistory_wishlist_review_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductView',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
